# Generated by Django 4.1.7 on 2023-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('ctx_text', models.TextField(null=True)),
                ('ctx_image', models.ImageField(null=True, upload_to='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '블로그',
            },
        ),
    ]
